  
name: domain_classifier_model_deploy
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: model_training
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          META_ENDPOINT: ${{ secrets.META_ENDPOINT }}
        run: |
            apt-get install python3-dev
            pip install --upgrade pip && pip install -r requirements.txt && pip install -r requirements_model.txt
            python setup.py install
            cd nlu_flow/sentence_classification/domain_classifier && pip install -r requirements.txt && python sklearn_domain_classifier.py && cp * ../../../
            # Write your CML report
            cml-send-comment report.md
      - name: Push Docker image to GitHub Packages
        uses: docker/build-push-action@v1
        with:
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
            registry: docker.pkg.github.com
            repository: nlu_flow/sentence_classification/domain_classifier
            tag_with_ref: true
            # docker login https://docker.pkg.github.com -u USERNAME --password-stdin
            
      
